# Generated by Django 5.1 on 2025-02-27 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0003_religion_section_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=50)),
                ('F_email', models.EmailField(max_length=254)),
                ('F_mobile', models.CharField(help_text='Enter a valid 10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('F_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hod_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_branch', to='Hitam_gatepass.branch')),
                ('Hod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_id', to='Hitam_gatepass.faculty')),
                ('Hod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_name', to='Hitam_gatepass.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_branch', to='Hitam_gatepass.branch')),
                ('M_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_id', to='Hitam_gatepass.faculty')),
                ('M_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_name', to='Hitam_gatepass.faculty')),
                ('M_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_section', to='Hitam_gatepass.section')),
                ('M_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_year', to='Hitam_gatepass.year')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_roll', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_img', models.URLField(blank=True, null=True)),
                ('s_attendec_present', models.IntegerField()),
                ('s_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_branch', to='Hitam_gatepass.branch')),
                ('s_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mentor', to='Hitam_gatepass.mentor')),
                ('s_religian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_religion', to='Hitam_gatepass.religion')),
                ('s_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_section', to='Hitam_gatepass.section')),
                ('s_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_year', to='Hitam_gatepass.year')),
            ],
        ),
        migrations.CreateModel(
            name='Gatepass',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_purpose', models.TextField()),
                ('g_type', models.CharField(max_length=50)),
                ('g_out_time', models.TimeField(auto_now_add=True)),
                ('g_in_time', models.TimeField(auto_now_add=True)),
                ('g_status', models.CharField(default='Not Approved', max_length=50)),
                ('g_date', models.DateField(auto_now_add=True)),
                ('g_time', models.TimeField(auto_now_add=True)),
                ('g_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses_as_rol', to='Hitam_gatepass.students')),
                ('g_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses_as_student', to='Hitam_gatepass.students')),
            ],
        ),
    ]
