# Generated by Django 5.1 on 2025-02-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0005_alter_gatepass_g_in_time_alter_gatepass_g_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_code',
        ),
    ]
