# Generated by Django 5.1 on 2025-02-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0006_remove_branch_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='F_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hod',
            name='Hod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_name', to='Hitam_gatepass.faculty', to_field='F_name'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='M_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_name', to='Hitam_gatepass.faculty', to_field='F_name'),
        ),
    ]
