# Generated by Django 5.1 on 2025-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0007_alter_faculty_f_name_alter_hod_hod_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('G_id', models.AutoField(primary_key=True, serialize=False)),
                ('G_name', models.CharField(max_length=50)),
            ],
        ),
    ]
