# Generated by Django 5.1 on 2025-03-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0008_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='F_gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_gender', to='Hitam_gatepass.gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='s_gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_gender', to='Hitam_gatepass.gender'),
            preserve_default=False,
        ),
    ]
