# Generated by Django 5.1 on 2025-03-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0009_faculty_f_gender_students_s_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='F_gender',
        ),
    ]
