# Generated by Django 5.1.7 on 2025-04-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0011_faculty_f_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='s_img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='s_mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hitam_gatepass.mentor'),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_roll',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
