# Generated by Django 5.1.7 on 2025-04-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0012_alter_students_s_img_alter_students_s_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='s_mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Hitam_gatepass.mentor'),
        ),
    ]
