# Generated by Django 5.1.7 on 2025-04-09 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hitam_gatepass', '0013_alter_students_s_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='s_attendec_present',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
